/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gst_bhawani;

import java.awt.Component;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.Calendar;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class BillLast extends javax.swing.JFrame {

    /**
     * Creates new form BillLast
     */
    public BillLast() {
        initComponents();
        getInvoiceNo();
        setLocationRelativeTo(null);
        setResizable(false);
    }
    
    public void getInvoiceNo()
    {
        try 
        {
        MySqlConnection my = new MySqlConnection();
        
        PreparedStatement ptmt = MySqlConnection.conn.prepareStatement("select * from bill_entry where Invoice_No=(select max(Invoice_No) from bill_entry)"); // get last row value from db.
        
        String s=null;
        ResultSet rs = ptmt.executeQuery();
        while(rs.next())
             s = rs.getString("Invoice_No");
        
        int s_int = Integer.parseInt(s);
        invoiceno.setText(Integer.toString((s_int)+1));
        MySqlConnection.conn.close();
        }
        catch(SQLException e)
        {
            System.out.println(e);
        } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        billEntry = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        transaction = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        printlabel = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        invoprint = new javax.swing.JTextField();
        bill_panel = new javax.swing.JPanel();
        bill_panel3 = new javax.swing.JPanel();
        billLayout = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        taxPer = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        mobileNo = new javax.swing.JTextField();
        customerName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        invoiceno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        sgstVal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cgstVal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        totalTax = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        sgst = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        cgst = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        discount = new javax.swing.JComboBox<>();
        percent = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        totalPrice = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        Save = new javax.swing.JButton();
        addr = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        aadharnotext = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        gstintext = new javax.swing.JTextField();
        transactionLayout = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        datecom = new javax.swing.JComboBox<>();
        monthcom = new javax.swing.JComboBox<>();
        yearcom = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablelist = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        amount1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        totalprice = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        billEntry.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        billEntry.setForeground(new java.awt.Color(255, 255, 255));
        billEntry.setText("New Bill Entry");
        billEntry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        billEntry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billEntryMouseClicked(evt);
            }
        });
        jPanel1.add(billEntry, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 170, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gst_bhawani/images/icons8_Purchase_Order_26px_1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 30, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gst_bhawani/images/icons8_Combo_Chart_26px_1.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 30, 40));

        transaction.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        transaction.setForeground(new java.awt.Color(255, 255, 255));
        transaction.setText("Transaction");
        transaction.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transaction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transactionMouseClicked(evt);
            }
        });
        jPanel1.add(transaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 140, -1));

        logout.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Log out");
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 20, 110, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gst_bhawani/images/icons8_Logout_Rounded_Left_26px_1.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 20, 30, 30));

        printlabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        printlabel.setForeground(new java.awt.Color(255, 255, 255));
        printlabel.setText("Print");
        printlabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        printlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printlabelMouseClicked(evt);
            }
        });
        jPanel1.add(printlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, 60, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gst_bhawani/images/icons8_Print_26px.png"))); // NOI18N
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, 30, 30));

        invoprint.setBackground(new java.awt.Color(0, 0, 102));
        invoprint.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        invoprint.setForeground(new java.awt.Color(255, 255, 255));
        invoprint.setBorder(null);
        jPanel1.add(invoprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 70, 30));

        bill_panel.setBackground(new java.awt.Color(102, 255, 255));
        bill_panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        bill_panel3.setBackground(new java.awt.Color(102, 255, 255));
        bill_panel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        bill_panel3.setLayout(new java.awt.CardLayout());

        billLayout.setBackground(new java.awt.Color(51, 0, 51));
        billLayout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        billLayout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Invoice No");
        billLayout.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 90, 30));

        taxPer.setBackground(new java.awt.Color(51, 0, 51));
        taxPer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        taxPer.setForeground(new java.awt.Color(51, 255, 51));
        taxPer.setBorder(null);
        billLayout.add(taxPer, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, 40, 30));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Product Name", "HSN Code", "Serial No", "Qty", "Price", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);

        billLayout.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 770, 250));

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("%");
        billLayout.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 30, 30));

        mobileNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mobileNo.setForeground(new java.awt.Color(255, 0, 0));
        billLayout.add(mobileNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 200, 30));

        customerName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        customerName.setForeground(new java.awt.Color(255, 0, 0));
        billLayout.add(customerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 240, 30));

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Customer Name");
        billLayout.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 130, 30));

        jLabel7.setBackground(new java.awt.Color(102, 102, 102));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mobile No");
        billLayout.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 130, 30));

        invoiceno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        invoiceno.setForeground(new java.awt.Color(255, 0, 0));
        billLayout.add(invoiceno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 110, 30));

        jLabel8.setBackground(new java.awt.Color(102, 102, 102));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tax");
        billLayout.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 50, 30));

        sgstVal.setBackground(new java.awt.Color(51, 0, 51));
        sgstVal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sgstVal.setForeground(new java.awt.Color(204, 255, 255));
        sgstVal.setBorder(null);
        sgstVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sgstValActionPerformed(evt);
            }
        });
        billLayout.add(sgstVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, 100, 30));

        jLabel9.setBackground(new java.awt.Color(102, 102, 102));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("SGST");
        billLayout.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, 50, 30));

        jLabel10.setBackground(new java.awt.Color(102, 102, 102));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CGST");
        billLayout.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, 60, 30));

        cgstVal.setBackground(new java.awt.Color(51, 0, 51));
        cgstVal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cgstVal.setForeground(new java.awt.Color(204, 255, 255));
        cgstVal.setBorder(null);
        billLayout.add(cgstVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 530, 110, 30));

        jLabel11.setBackground(new java.awt.Color(102, 102, 102));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Total Tax");
        billLayout.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 530, 80, 30));

        totalTax.setBackground(new java.awt.Color(51, 0, 51));
        totalTax.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalTax.setForeground(new java.awt.Color(204, 255, 255));
        totalTax.setBorder(null);
        billLayout.add(totalTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 530, 120, 30));

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("GSTIN/UIN");
        billLayout.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 120, -1));

        sgst.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        sgst.setForeground(new java.awt.Color(51, 0, 51));
        sgst.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        sgst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sgstActionPerformed(evt);
            }
        });
        billLayout.add(sgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 130, 100, 30));

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("%");
        billLayout.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 200, 30, 30));

        cgst.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        cgst.setForeground(new java.awt.Color(51, 0, 51));
        cgst.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        cgst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cgstActionPerformed(evt);
            }
        });
        billLayout.add(cgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 200, 100, 30));

        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("%");
        billLayout.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 130, 20, 30));

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("S-GST");
        billLayout.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 130, 60, 30));

        jLabel17.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("C-GST");
        billLayout.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 200, 60, 30));

        jLabel19.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Amount(T)");
        billLayout.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 270, 120, -1));

        amount.setBackground(new java.awt.Color(51, 0, 51));
        amount.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        amount.setForeground(new java.awt.Color(204, 255, 255));
        amount.setBorder(null);
        amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountActionPerformed(evt);
            }
        });
        billLayout.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 270, 150, 30));

        discount.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        discount.setForeground(new java.awt.Color(51, 0, 51));
        discount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "35", "40", "42", "44", "48", "50" }));
        discount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountActionPerformed(evt);
            }
        });
        billLayout.add(discount, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 340, 100, 30));

        percent.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        percent.setForeground(new java.awt.Color(255, 255, 255));
        percent.setText("%");
        billLayout.add(percent, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 340, 20, 30));

        jLabel16.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Discount");
        billLayout.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 340, 90, 30));

        jLabel18.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Total Price");
        billLayout.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 410, 110, -1));

        totalPrice.setBackground(new java.awt.Color(51, 0, 51));
        totalPrice.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        totalPrice.setForeground(new java.awt.Color(204, 255, 255));
        totalPrice.setBorder(null);
        totalPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalPriceActionPerformed(evt);
            }
        });
        billLayout.add(totalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 410, 160, 30));

        jLabel20.setBackground(new java.awt.Color(102, 102, 102));
        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Total ");
        billLayout.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, 50, 30));

        total.setBackground(new java.awt.Color(51, 0, 51));
        total.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        total.setForeground(new java.awt.Color(255, 255, 255));
        total.setBorder(null);
        billLayout.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 440, 120, 30));

        Save.setBackground(new java.awt.Color(0, 204, 0));
        Save.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        Save.setForeground(new java.awt.Color(255, 255, 255));
        Save.setText("Save");
        Save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        billLayout.add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 530, 90, -1));

        addr.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        billLayout.add(addr, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 142, 240, 30));

        jLabel24.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Address");
        billLayout.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 80, -1));

        aadharnotext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        billLayout.add(aadharnotext, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 240, 30));

        jLabel25.setFont(new java.awt.Font("Tempus Sans ITC", 1, 20)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Aadhar No");
        billLayout.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 110, -1));

        gstintext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        billLayout.add(gstintext, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 240, 30));

        bill_panel3.add(billLayout, "card2");

        transactionLayout.setBackground(new java.awt.Color(255, 255, 255));
        transactionLayout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        transactionLayout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 153, 0));
        jLabel21.setText("Date");
        transactionLayout.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 60, -1));

        datecom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        datecom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DD", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        transactionLayout.add(datecom, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 80, 30));

        monthcom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        monthcom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MM", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        transactionLayout.add(monthcom, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 80, 30));

        yearcom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        yearcom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YYYY", "2018", "2019", "2020", "2021", "2022", "2023" }));
        yearcom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearcomActionPerformed(evt);
            }
        });
        transactionLayout.add(yearcom, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, 100, 30));

        tablelist.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tablelist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invoice_No", "Cus_Name", "Cus_Mobile", "Address", "S-GST", "C-GST", "Amount Tax", "Discount", "Total Price"
            }
        ));
        tablelist.setRowHeight(30);
        jScrollPane2.setViewportView(tablelist);

        transactionLayout.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 1080, 380));

        jLabel22.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 153, 0));
        jLabel22.setText("Amount Tax Total");
        transactionLayout.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 170, -1));

        amount1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        amount1.setForeground(new java.awt.Color(0, 0, 153));
        amount1.setBorder(null);
        amount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amount1ActionPerformed(evt);
            }
        });
        transactionLayout.add(amount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 190, 30));

        jLabel23.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 153, 0));
        jLabel23.setText("Total Price total");
        transactionLayout.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 540, 150, -1));

        totalprice.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        totalprice.setForeground(new java.awt.Color(255, 0, 0));
        totalprice.setBorder(null);
        totalprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalpriceActionPerformed(evt);
            }
        });
        transactionLayout.add(totalprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 530, 190, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Product Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        transactionLayout.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 530, -1, -1));

        bill_panel3.add(transactionLayout, "card2");

        javax.swing.GroupLayout bill_panelLayout = new javax.swing.GroupLayout(bill_panel);
        bill_panel.setLayout(bill_panelLayout);
        bill_panelLayout.setHorizontalGroup(
            bill_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bill_panel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bill_panelLayout.setVerticalGroup(
            bill_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bill_panelLayout.createSequentialGroup()
                .addComponent(bill_panel3, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bill_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bill_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void billEntryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billEntryMouseClicked
        // TODO add your handling code here:
        bill_panel3.removeAll();
        bill_panel3.repaint();
        bill_panel3.revalidate();
        
        bill_panel3.add(billLayout);
        bill_panel3.repaint();
        bill_panel3.revalidate();
        valuereset();
        getInvoiceNo();
        
    }//GEN-LAST:event_billEntryMouseClicked
    public void valuereset()
    {
        customerName.setText("");
        mobileNo.setText("");
        amount.setText("");
        totalPrice.setText("");
        total.setText("");
        taxPer.setText("");
        sgstVal.setText("");
        cgstVal.setText("");
        totalTax.setText("");
        cgst.setSelectedIndex(0);
        sgst.setSelectedIndex(0);
        addr.setText("");
        discount.setSelectedIndex(0);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
      //  model.getDataVector().removeAllElements();
      
       for (int i = 0; i < model.getRowCount(); i++) {
        for (int j = 0; j < model.getColumnCount(); j++) {
            model.setValueAt("", i, j);
        }
    }
      
    }
    
    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        LogIn lg = new LogIn();
        lg.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void transactionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionMouseClicked
        // TODO add your handling code here:
        bill_panel3.removeAll();
        bill_panel3.repaint();
        bill_panel3.revalidate();
        
        bill_panel3.add(transactionLayout);
        bill_panel3.repaint();
        bill_panel3.revalidate();
        yearcom.setSelectedIndex(0);
        datecom.setSelectedIndex(0);
        monthcom.setSelectedIndex(0);
        amount1.setText("");
        totalprice.setText("");
        DefaultTableModel model = (DefaultTableModel) tablelist.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_transactionMouseClicked

    private void sgstValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sgstValActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sgstValActionPerformed

    private void sgstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sgstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sgstActionPerformed
    int row;
    private void cgstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cgstActionPerformed
        // TODO add your handling code here:
        String c_gst = cgst.getSelectedItem().toString();
        if(!"select".equals(c_gst))
        {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        String s1,s2;
        double tot=0.0;
        for(row=0;row<50;row++)
        {
            try 
            {
                s1 = jTable1.getModel().getValueAt(row, 4).toString();
            }
            catch(Exception e)
            {
                break;
            }
            if("".equals(s1))
                break;
            s2 = jTable1.getModel().getValueAt(row,5).toString();
            int q = Integer.parseInt(s1);
            double p = Double.parseDouble(s2);
            
            model.setValueAt(new DecimalFormat("##.##").format(p*q),row,6);
            tot += (p*q);
        }
        total.setText(new DecimalFormat("##.##").format(tot));
        total.setEditable(false);
        String s_gst = sgst.getSelectedItem().toString();
        if(tot!=0 && !"select".equals(s_gst))
        {
            int sgsst = Integer.parseInt(s_gst);
            int cgsst = Integer.parseInt(cgst.getSelectedItem().toString());
            taxPer.setText(Integer.toString(sgsst+cgsst));
            taxPer.setEditable(false);
         //   if("GST".equals(taxx))
           // {
                double res = tot + (tot * (sgsst+cgsst)/100.00);

                amount.setText(new DecimalFormat("##.##").format(res));
                amount.setEditable(false);
                totalPrice.setText(new DecimalFormat("##.##").format(res));
                totalPrice.setEditable(false);
                double t1 = tot*(sgsst)/100.00;
                sgstVal.setText(new DecimalFormat("##.##").format(t1));
                sgstVal.setEditable(false);
                double t2 = tot*(cgsst)/100.00;
                cgstVal.setText(new DecimalFormat("##.##").format(t2));
                cgstVal.setEditable(false);
                double t3 = tot*(cgsst+sgsst)/100.00;
                totalTax.setText(new DecimalFormat("##.##").format(t3));
                totalTax.setEditable(false);
           // }
        /*    if("Reverse GST".equals(taxx))
            {
                double res =(tot *100)/(100.00 + (sgsst+cgsst));

                amount.setText(new DecimalFormat("##.##").format(res));
                totalPrice.setText(Double.toString(tot));
                discount.setVisible(false);
                percent.setVisible(false);
                double t4 = res*(sgsst)/100.00;
                sgstVal.setText(new DecimalFormat("##.##").format(t4));
                double t5 = res*(cgsst)/100.00;
                cgstVal.setText(new DecimalFormat("##.##").format(t5));
                double t6 = res*(cgsst+sgsst)/100.00;
                totalTax.setText(new DecimalFormat("##.##").format(t6));
            }*/

        }
        else
        JOptionPane.showMessageDialog(null, "please select before Rate, quantity, tax and S-GST options ..!!!");
        }
        
    }//GEN-LAST:event_cgstActionPerformed

    private void amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountActionPerformed

    private void discountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountActionPerformed
        // TODO add your handling code here:
        String dis = discount.getSelectedItem().toString();
        if(!"0".equals(dis))
        {
     //   if("GST".equals(tax.getSelectedItem().toString()))
      //  {
            double amt = Double.parseDouble(amount.getText());
            int dst = Integer.parseInt(dis);
            double less = amt - (amt * dst/100.00);
            //  less =Double.parseDouble(new DecimalFormat("##.##").format(less));
            // totalPrice.setText(Double.toString(less));
            totalPrice.setText(new DecimalFormat("##.##").format(less));
            totalPrice.setEditable(false);
//  }
        //else
      //  JOptionPane.showMessageDialog(null, "You are in Reverse GST Mode  ..!!!"); 
        }
    }//GEN-LAST:event_discountActionPerformed

    private void totalPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalPriceActionPerformed
    
    PreparedStatement prepstmt=null;
    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        String C_No = invoiceno.getText();
        String C_Name = customerName.getText();
        String mob = mobileNo.getText();
      
        String adds = addr.getText();
        String S_gst = sgst.getSelectedItem().toString();
        String C_gst = cgst.getSelectedItem().toString();
        String amnt = amount.getText();
        String dis = discount.getSelectedItem().toString();
        String tot = totalPrice.getText();
        String gstin = gstintext.getText();
        String aadhar = aadharnotext.getText();
        

        // Date

        Calendar calendar = Calendar.getInstance();
        java.sql.Date startDate = new java.sql.Date(calendar.getTime().getTime());

        // connectiong database.............
        try
        {
            MySqlConnection my = new MySqlConnection();

            /*  ptmt = MySqlConnection.conn.prepareStatement("select * from bill_entry where Customer_No=(select max(Customer_No) from bill_entry)"); // get last row value from db.

            String s=null;
            rs = ptmt.executeQuery();
            while(rs.next())
            s = rs.getString("Customer_No");

            int s_int = Integer.parseInt(s);
            C_No = Integer.toString((s_int)+1); */

            for(int j=0;j<row;j++)
            {
                String pname = (String)jTable1.getValueAt(j,1);
                String hsncode = (String)jTable1.getValueAt(j,2);
                String serno = (String)jTable1.getValueAt(j,3);
                String qty = (String)jTable1.getValueAt(j,4);
                String price = (String)jTable1.getValueAt(j,5);
                String tott = (String)jTable1.getValueAt(j,6);
                
                String sql = "INSERT INTO product_details (Invoice_No, Product_Name, HSN_Code, Serial_No, Quantity, Price, Total)" + " values (?,?,?,?,?,?,?)";
                prepstmt = MySqlConnection.conn.prepareStatement(sql);
               
                prepstmt.setString(1, C_No);
                prepstmt.setString(2, pname);
                prepstmt.setString(3, hsncode);
                prepstmt.setString(4, serno);
                prepstmt.setString(5, qty);
                prepstmt.setString(6, price);
                prepstmt.setString(7, tott);
                
                boolean k = prepstmt.execute();
                if(!k)
                    System.out.println("Table value inserted");
                else
                    System.out.println("Error");
            }
            
            
            String query = "INSERT INTO bill_entry (Invoice_No, Customer_Name, Mobile_No, Date, Address, S_GST, C_GST, Amount_Tax, Discount, Total_Price,Aadhar_No,GSTIN_No)" + " values (?,?,?,?,?,?,?,?,?,?,?,?)";

            prepstmt = MySqlConnection.conn.prepareStatement(query);

            prepstmt.setString(1, C_No);
            prepstmt.setString(2, C_Name);
            prepstmt.setString(3, mob);
            prepstmt.setDate(4, startDate);
            prepstmt.setString(5, adds);
            prepstmt.setString(6, S_gst);
            prepstmt.setString(7, C_gst);
            prepstmt.setString(8, amnt);
            prepstmt.setString(9, dis);
            prepstmt.setString(10, tot);
            prepstmt.setString(11, aadhar);
            prepstmt.setString(12, gstin);
            
            boolean i = prepstmt.execute();
            
            
            System.out.println(i);
            if(i)
            {
                JOptionPane.showMessageDialog(null, "Data is  NOT  saved in database");
            }
            else
            JOptionPane.showMessageDialog(null, "Save Successfully..!!");

        }
        catch(SQLException se)
        {
            System.out.println(se);
        } 
       System.out.println(row);
    }//GEN-LAST:event_SaveActionPerformed
    PreparedStatement ptmt=null;
    ResultSet rs = null;
    private void yearcomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearcomActionPerformed
        // TODO add your handling code here:
        String Y = yearcom.getSelectedItem().toString();
        if(!"YYYY".equals(Y))
        {
        String D = datecom.getSelectedItem().toString();
        String M = monthcom.getSelectedItem().toString();
        
        if(!"DD".equals(D) && !"MM".equals(M))
        {
            String dates = Y + "-" + M + "-" + D;
            System.out.println(dates);

            DefaultTableModel model = (DefaultTableModel) tablelist.getModel();
            model.setRowCount(0);
            // connecting database................................
            double amtt = 0.0,tpt=0.0;
            try
            {
               MySqlConnection my = new MySqlConnection();

                ptmt = MySqlConnection.conn.prepareStatement("select * from bill_entry where Date=?"); // get last row value from db.
                ptmt.setString(1, dates);
                rs = ptmt.executeQuery();
                while(rs.next())
                {
                    model.addRow(new Object[]{rs.getString("Invoice_No"),rs.getString("Customer_Name"),rs.getString("Mobile_No"),rs.getString("Address"),rs.getString("S_GST"),rs.getString("C_GST"),rs.getString("Amount_Tax"),rs.getString("Discount"),rs.getString("Total_Price")});
                    amtt += Double.parseDouble(rs.getString("Amount_Tax"));
                    tpt += Double.parseDouble(rs.getString("Total_Price"));
                }
               amount1.setText(new DecimalFormat("##.##").format(amtt));
               totalprice.setText(new DecimalFormat("##.##").format(tpt));
                MySqlConnection.conn.close();
                
            }
            catch(SQLException e)
            {
                System.out.println(e);
            }
        }
        else
        JOptionPane.showMessageDialog(null, "please select date and month before..!!!");
        }
    }//GEN-LAST:event_yearcomActionPerformed

    private void amount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amount1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amount1ActionPerformed

    private void totalpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalpriceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TransactionReport tr = new TransactionReport();
        tr.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void printlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printlabelMouseClicked
        // TODO add your handling code here:
        String passval = invoprint.getText();
        PrintInterface pf = new PrintInterface(passval);
        pf.setVisible(true);
    }//GEN-LAST:event_printlabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillLast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillLast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillLast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillLast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillLast().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Save;
    private javax.swing.JTextField aadharnotext;
    private javax.swing.JTextField addr;
    private javax.swing.JTextField amount;
    private javax.swing.JTextField amount1;
    private javax.swing.JLabel billEntry;
    private javax.swing.JPanel billLayout;
    private javax.swing.JPanel bill_panel;
    private javax.swing.JPanel bill_panel3;
    private javax.swing.JComboBox<String> cgst;
    private javax.swing.JTextField cgstVal;
    private javax.swing.JTextField customerName;
    private javax.swing.JComboBox<String> datecom;
    private javax.swing.JComboBox<String> discount;
    private javax.swing.JTextField gstintext;
    public javax.swing.JTextField invoiceno;
    public javax.swing.JTextField invoprint;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel logout;
    private javax.swing.JTextField mobileNo;
    private javax.swing.JComboBox<String> monthcom;
    private javax.swing.JLabel percent;
    private javax.swing.JLabel printlabel;
    private javax.swing.JComboBox<String> sgst;
    private javax.swing.JTextField sgstVal;
    private javax.swing.JTable tablelist;
    private javax.swing.JTextField taxPer;
    private javax.swing.JTextField total;
    private javax.swing.JTextField totalPrice;
    private javax.swing.JTextField totalTax;
    private javax.swing.JTextField totalprice;
    private javax.swing.JLabel transaction;
    private javax.swing.JPanel transactionLayout;
    private javax.swing.JComboBox<String> yearcom;
    // End of variables declaration//GEN-END:variables
}
